
NDefines.NGame.START_DATE = "1935.1.1.12"			--Vanilla "1936.1.1.12
NDefines.NGame.END_DATE = "1950.1.1.1"				--Vanilla 1949.1.1.1

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 2000;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 2000;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 2000;

NDefines.NCountry.NUCLEAR_PRODUCTION_SCALE = 730					-- +1 nuclear_production gives 1 nuke per year. Vanilla 365.

NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.0		-- The baseline for what the AI considers the world is getting dangerous and we want to generate wargoals with no antagonize value. Vanilla 1.0
NDefines.NAI.FORCE_FACTOR_AGAINST_EXTRA_MINOR = 0.4			-- AI considers generating wargoals against minors below this % of force compared to themselves to get at a bigger enemy. Vanilla 0.15
NDefines.NAI.DECLARE_WAR_RELATIVE_FORCE_FACTOR = 0.4	-- Weight of relative force between nations that consider going to war. Vanilla 0.5
NDefines.NAI.DECLARE_WAR_NOT_NEIGHBOR_FACTOR = 10.0		-- Multiplier applied before force factor if country is not neighbor with the one it is considering going to war. Vanilla 0.25
NDefines.NDiplomacy.TENSION_NO_CB_WAR = 5				-- Amount of tension generated by a no-CB wargoal. Vanilla 10
NDefines.NDiplomacy.TENSION_CB_WAR = 2					-- Amount of tension generated by a war with a CB. Vanilla 7
NDefines.NDiplomacy.TENSION_DECAY_DAILY = 0.015			-- Each day tension decays this much for Threat sources which are no longer relevant. Vanilla 0.005
NDefines.NCountry.NUCLEAR_PRODUCTION_SCALE = 2190					-- +1 nuclear_production gives 1 nuke per year. Vanilla 365. (currently at 6 years)

NDefines.NProduction.INFRA_MAX_CONSTRUCTION_COST_EFFECT = 1 		-- Building in a state with higher infrastructure will reduce the cost of shared buildings. Vanilla 1
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 3.5			-- Vanilla 2.5

NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 24		-- Vanilla 24
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 24			-- Vanilla 24



NDefines.NAI.DESIRE_USE_XP_TO_UPDATE_LAND_TEMPLATE = 100.0 -- Vanilla 2.0 How quickly is desire to update/create templates accumulated?
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_LAND_EQUIPMENT = 2.0  -- Vanilla 1.0 How quickly is desire to update/create land equipment variants accumulated?
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_NAVAL_EQUIPMENT = 100.0 -- Vanilla 1.0 How quickly is desire to update/create naval equipment variants accumulated?
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_AIR_EQUIPMENT = 100.0   -- Vanilla 1.0 How quickly is desire to update/create air equipment variants accumulated?



NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.25 -- Vanilla 0.1
NDefines.NAI.UPGRADES_DEFICIT_LIMIT_DAYS = 180 -- Vanilla 50 Ai will avoid upgrading units in the field to new templates if it takes longer than this to fullfill their equipment need

